In [13]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta, date
import matplotlib.pyplot as plt
import seaborn as sns
################################################
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression


In [2]:
url = 'https://raw.githubusercontent.com/PacktPublishing/Data-Science-for-Marketing-Analytics-Second-Edition/master/Chapter07/Exercise7.01/Shill_Bidding_Dataset.csv'

In [4]:
shilling = pd.read_csv(url)

In [6]:
shilling.drop(['Record_ID', 'Auction_ID', 'Bidder_ID'], axis=1, inplace=True)

In [7]:
shilling.head()

Bidder_Tendency  Bidding_Ratio  Successive_Outbidding  Last_Bidding  \
0         0.200000       0.400000                    0.0      0.000028   
1         0.024390       0.200000                    0.0      0.013123   
2         0.142857       0.200000                    0.0      0.003042   
3         0.100000       0.200000                    0.0      0.097477   
4         0.051282       0.222222                    0.0      0.001318   

   Auction_Bids  Starting_Price_Average  Early_Bidding  Winning_Ratio  \
0           0.0                0.993593       0.000028       0.666667   
1           0.0                0.993593       0.013123       0.944444   
2           0.0                0.993593       0.003042       1.000000   
3           0.0                0.993593       0.097477       1.000000   
4           0.0                0.000000       0.001242       0.500000   

   Auction_Duration  Class  
0                 5      0  
1                 5      0  
2                 5      0  
3                 5      0  
4                 7      0

In [8]:
shilling['Class'].unique()

array([0, 1], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split

X = shilling.drop("Class",axis=1)
y = shilling["Class"]
# Split the dataset into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,\
 random_state=1, stratify=y)


In [10]:
print("Training dataset size: {}, Testing dataset size: {}"\
 .format(X_train.shape,X_test.shape))

Training dataset size: (4424, 9), Testing dataset size: (1897, 9)


In [14]:
linear = LinearRegression()
linear.fit(X_train,y_train)

LinearRegression()

In [15]:
linear.predict(X_test)[:10]

array([-0.00375542, -0.00248633, -0.01090699, -0.02753235,  0.01939224,
        0.99493654,  0.02761226, -0.00565047,  0.48101551,  0.00471959])

In [16]:
y_test[:10].values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [17]:
print("Score on training dataset: {}, "\
 "Score on testing dataset: {}"\
 .format(linear.score(X_train,y_train),\
 linear.score(X_test,y_test)))

Score on training dataset: 0.8166836356918418, Score on testing dataset: 0.8119909602893054


In [18]:
# now trying the logistic regression model
logit = LogisticRegression()
logit.fit(X_train, y_train)

LogisticRegression()

In [21]:
print("Score on training dataset: {}, "\
 "Score on testing dataset: {}"\
 .format(logit.score(X_train,y_train),\
 logit.score(X_test,y_test)))

Score on training dataset: 0.9794303797468354, Score on testing dataset: 0.9715340010542962
